<a href="https://colab.research.google.com/github/mefy-Aruna/Diabetes/blob/main/PIMA_DATASET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
# import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'data.csv')
df

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [3]:
df

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [4]:
x = df.iloc[:, 0:8].values
y = df.iloc[:, 8].values

In [5]:
x


array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [7]:
#@title CLASSIFIER1:KNN


In [8]:
# Train Test Split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier



In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

In [10]:
x_train

array([[0.00e+00, 1.05e+02, 6.80e+01, ..., 2.00e+01, 2.36e-01, 2.20e+01],
       [2.00e+00, 1.05e+02, 8.00e+01, ..., 3.37e+01, 7.11e-01, 2.90e+01],
       [8.00e+00, 1.88e+02, 7.80e+01, ..., 4.79e+01, 1.37e-01, 4.30e+01],
       ...,
       [3.00e+00, 1.93e+02, 7.00e+01, ..., 3.49e+01, 2.41e-01, 2.50e+01],
       [7.00e+00, 9.40e+01, 6.40e+01, ..., 3.33e+01, 7.38e-01, 4.10e+01],
       [9.00e+00, 5.70e+01, 8.00e+01, ..., 3.28e+01, 9.60e-02, 4.10e+01]])

In [11]:
# Preprocessing

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [12]:
KNNclassifier = KNeighborsClassifier(n_neighbors = 20)
KNNclassifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=20, p=2,
                     weights='uniform')

In [13]:
y_pred = KNNclassifier.predict(x_test)

In [14]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('KNN acc:',accuracy_score(y_test, y_pred))

[[91  7]
 [26 30]]
              precision    recall  f1-score   support

           0       0.78      0.93      0.85        98
           1       0.81      0.54      0.65        56

    accuracy                           0.79       154
   macro avg       0.79      0.73      0.75       154
weighted avg       0.79      0.79      0.77       154

KNN acc: 0.7857142857142857


In [15]:
#@title CLASSIFIER 2:DECISION TREE





In [16]:
#from sklearn.model_selection import train_test_split
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [17]:
from sklearn.tree import DecisionTreeClassifier
Decclassifier = DecisionTreeClassifier(criterion="entropy", max_depth = 5)
Decclassifier 

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [18]:

Decclassifier.fit(x_train,y_train)
y_pred = Decclassifier.predict(x_test)

In [19]:
from sklearn import metrics
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, y_pred))

DecisionTrees's Accuracy:  0.7597402597402597


In [20]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('DecisionTree acc:',accuracy_score(y_test, y_pred))

[[72 26]
 [11 45]]
              precision    recall  f1-score   support

           0       0.87      0.73      0.80        98
           1       0.63      0.80      0.71        56

    accuracy                           0.76       154
   macro avg       0.75      0.77      0.75       154
weighted avg       0.78      0.76      0.76       154

DecisionTree acc: 0.7597402597402597


In [21]:
#@title CLASSIFIER 3:SVM


In [22]:

# Polynomial Kernel
from sklearn.svm import SVC   # Support Vector Classifier
SVMclassifier = SVC(kernel ='rbf')
SVMclassifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [23]:
x_train

array([[-1.14153231, -0.48468727, -0.04643521, ..., -1.54224606,
        -0.72330956, -0.93786998],
       [-0.53469176, -0.48468727,  0.57562779, ...,  0.20097692,
         0.72572421, -0.34473208],
       [ 1.2858299 ,  2.15342365,  0.47195062, ...,  2.00782118,
        -1.02531871,  0.84154372],
       ...,
       [-0.23127148,  2.31234599,  0.05724195, ...,  0.35366798,
        -0.70805658, -0.68366802],
       [ 0.98240962, -0.83431642, -0.25378955, ...,  0.1500799 ,
         0.80809034,  0.67207575],
       [ 1.58925018, -2.01034177,  0.57562779, ...,  0.08645862,
        -1.1503932 ,  0.67207575]])

In [24]:
y_pred = SVMclassifier.predict(x_test)

In [25]:
# Evaluating the Algorithm
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[89  9]
 [19 37]]
              precision    recall  f1-score   support

           0       0.82      0.91      0.86        98
           1       0.80      0.66      0.73        56

    accuracy                           0.82       154
   macro avg       0.81      0.78      0.79       154
weighted avg       0.82      0.82      0.81       154

0.8181818181818182


In [26]:
#@title Classifier 4: Random Forest 


In [27]:
# Train the Algorithm
from sklearn.ensemble import RandomForestClassifier
RFclassifier = RandomForestClassifier(n_estimators = 20)
RFclassifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [28]:

y_pred = RFclassifier.predict(x_test)

In [29]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[79 19]
 [17 39]]
              precision    recall  f1-score   support

           0       0.82      0.81      0.81        98
           1       0.67      0.70      0.68        56

    accuracy                           0.77       154
   macro avg       0.75      0.75      0.75       154
weighted avg       0.77      0.77      0.77       154

0.7662337662337663


In [30]:
# Train the Algorithm
RF1classifier = RandomForestClassifier(n_estimators = 75)
RF1classifier.fit(x_train, y_train)

y_pred = RF1classifier.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[82 16]
 [13 43]]
              precision    recall  f1-score   support

           0       0.86      0.84      0.85        98
           1       0.73      0.77      0.75        56

    accuracy                           0.81       154
   macro avg       0.80      0.80      0.80       154
weighted avg       0.81      0.81      0.81       154

0.8116883116883117


In [32]:
#@title Classifier 5: LOGISTIC REGRESSION


In [33]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(C=0.009, solver='liblinear')
LR.fit(x_train,y_train)

LogisticRegression(C=0.009, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:

LR_pred = LR.predict(x_test)

In [35]:
print(confusion_matrix(y_test, LR_pred))
print(classification_report(y_test, LR_pred))
print(accuracy_score(y_test, LR_pred))

[[83 15]
 [15 41]]
              precision    recall  f1-score   support

           0       0.85      0.85      0.85        98
           1       0.73      0.73      0.73        56

    accuracy                           0.81       154
   macro avg       0.79      0.79      0.79       154
weighted avg       0.81      0.81      0.81       154

0.8051948051948052


In [36]:
#@title CLASSIFIER 7: GAUSSIAN


In [37]:
# import Gaussian Naive Bayes import GaussianNB
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier 
gnb = GaussianNB()

# Train the model using the training sets
gnb.fit(x_train, y_train)

# Predict the response for the test dataset
y_pred = gnb.predict(x_test)

In [38]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[83 15]
 [17 39]]
              precision    recall  f1-score   support

           0       0.83      0.85      0.84        98
           1       0.72      0.70      0.71        56

    accuracy                           0.79       154
   macro avg       0.78      0.77      0.77       154
weighted avg       0.79      0.79      0.79       154

0.7922077922077922


In [39]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7922077922077922


In [40]:
#@title CLASSIFIER 8: with LDA


In [41]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)
X_train = lda.fit_transform(x_train, y_train)
X_test = lda.transform(x_test)

In [42]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=100)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[78 20]
 [18 38]]
Accuracy0.7532467532467533


In [44]:
#@title CLASSIFIER 9: PERCEPTRON


In [45]:
from sklearn.linear_model import Perceptron

In [46]:
cls= Perceptron()
cls.fit(x_train,y_train)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [47]:
y_pred = cls.predict(x_test)

In [48]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[74 24]
 [15 41]]
              precision    recall  f1-score   support

           0       0.83      0.76      0.79        98
           1       0.63      0.73      0.68        56

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154

0.7467532467532467
